version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - mqtt
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  mqtt:
      container_name: mqtt
      image: eclipse-mosquitto
      ports:
        - "1884:1884"